name: Build and Test

on: ["push"]
jobs:
  build:
    uses: ./.github/workflows/docker.yml
    with:
      registry-dockerhub-enable: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      registry-repo-name: flutterbuilder
      registry-readme: ./README.md
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
